export * as cours from "./Tables/cours.js"
export * as coursbydate from "./Tables/coursbydate.js"
export * as events from "./Tables/events.js"
export * as users from "./Tables/users.js"
export * as adminUsers from "./Tables/adminUsers.js"
